version: '3.7'

services:
  app:
    # refers the directory to build image from
    build: app
    # declares port mapping, equivalent to docker run -p 80:80 ..
    ports:
      - 80:5000
    # container is only started once redis was started
    depends_on:
      db:
        condition: service_healthy
  db:
    # explictly sets a container name instead of defering it
    container_name: app_db
    # image is not build but pulled from registry, hence no build directive but image
    image: mariadb
    # defines environment vars, passed to the container
    environment:
      MYSQL_ROOT_PASSWORD: changeme # of course not a good idea..
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: changeme_too
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-udb_user", "-pchangeme_too"]
      interval: 5s
      timeout: 5s
      retries: 20