version: '3.7'

services:
  app:
    # refers the directory to build image from
    build: app
    # defines number of instances, equivalent to run docker compose up --scale app=3
    deploy:
      mode: replicated
      replicas: 3
    # container is only started once redis was started
    depends_on:
      - redis
  nginx:
    # explictly sets a container name instead of defering it
    container_name: nginx
    # image is not build but pulled from registry, hence no build directive but image
    image: nginx:latest
    # mount config
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # declares port mapping, equivalent to docker run -p 80:80 ..
    ports:
      - 80:80
    # container is only started once app was started
    depends_on:
      - app
  redis:
    # explictly sets a container name instead of defering it
    container_name: redis
    # image is not build but pulled from registry, hence no build directive but image
    image: redis:latest
