services:
  
  server:
    image: grpc-demo/server
    build:
      context: ../../
      dockerfile: build/package/Dockerfile
      target: server-dev
    container_name: server
    hostname: server
    ports:
      - "8081:8081"
    command: ["--port", "8081"]
  